# Generated by Django 3.2 on 2021-05-13 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_color_estado_marca_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('serie', models.CharField(max_length=70)),
                ('cod_inventario', models.IntegerField()),
                ('descripcion', models.CharField(max_length=70)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.color')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.estado')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.laboratorio')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.modelo')),
                ('padre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_equipos.equipo')),
            ],
        ),
    ]
